### ISSUE TITLE
Tenda Ax1803仿真

### ISSUE THREAD

**Issue by 1160300418** [zhefox/IOT_Vul#1]
您好，我有一些问题想在Tenda Ax1803上进行确认，请问您方便告诉我您的仿真方式吗？

**Comment by Ch4mpa9ne** [comment]
同求，学习一下

**Comment by zhefox** [comment]
简单模拟http的话，fimeAE即可



| |
ZHEFOX
|
|
***@***.***
|




---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2022年09月07日 18:43 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***> |
| 主题 | Re: [zhefox/IOT_Vul] Tenda Ax1803仿真 (Issue #1) |

同求，学习一下
